name:                simulation
version:             0.1.0.0
author:              "Hannes Feldt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simulation21#readme>

dependencies:
- base >= 4.7 && < 4.14
- Chart
- Chart-diagrams
- diagrams-svg
- diagrams-lib
- SVGFonts
- colour
- data-default-class
- lens
- random >= 1.2
- random-fu
- statistics
- mwc-random
- transformers
- grid
- mtl
- vector-split
- vector
- JuicyPixels
- split
- criterion

executables:
  simulation14-exe:
    main:                Main.hs
    source-dirs:         simulation14
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation16-exe:
    main:                Main.hs
    source-dirs:         simulation16
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation21-exe:
    main:                Main.hs
    source-dirs:         simulation21
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation22-exe:
    main:                Main.hs
    source-dirs:         simulation22
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation23-exe:
    main:                Main.hs
    source-dirs:         simulation23
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  cellular-automaton-exe:
    main:                Main.hs
    source-dirs:         cellular-automaton
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation31-exe:
    main:                Main.hs
    source-dirs:         simulation31
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simulation32-exe:
    main:                Main.hs
    source-dirs:         simulation32
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation41-exe:
    main:                Main.hs
    source-dirs:         simulation41
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation42-exe:
    main:                Main.hs
    source-dirs:         simulation42
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation43-exe:
    main:                Main.hs
    source-dirs:         simulation43
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation44-exe:
    main:                Main.hs
    source-dirs:         simulation44
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation45-exe:
    main:                Main.hs
    source-dirs:         simulation45
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation51-exe:
    main:                Main.hs
    source-dirs:         simulation51
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation52-exe:
    main:                Main.hs
    source-dirs:         simulation52
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  simulation53-exe:
    main:                Main.hs
    source-dirs:         simulation53
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

